version: '3'

services:
  db:
    image: postgres:11.2
  backend:
    build: ./Backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend/src:/src
    ports:
      - '8000:8000'
    depends_on:
      - db
  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend/:/app
      - frontend_build:/app/build
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - frontend_build:/var/www/frontend
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

volumes:
  frontend_build:
