version: '3'

services:
  db:
    image: postgres:11.2
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  backend:
    build: ./Backend
    volumes:
      - ./Backend/src:/src
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
  worker_channels:
    build: ./Backend
    command: python manage.py runworker --only-channels=http.* --only-channels=websocket.* -v2
    volumes:
      - ./Backend/src:/src
    depends_on:
      - db
      - redis
  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend/:/app
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend

volumes:
  frontend_build:
