version: '3'

services:
  db:
    env_file:
      - ./env/prod
  backend:
    env_file:
      - ./env/prod
  worker_channels:
    env_file:
      - ./env/prod
  frontend:
    volumes:
      - frontend_build:/app/build
    command: yarn build
  nginx:
    ports:
      - '80:80'
    volumes:
      - frontend_build:/var/www/frontend
      - ./nginx/nginx-proxy.prod.conf:/etc/nginx/conf.d/default.conf:ro
