version: '3'

services:
  db:
    env_file:
      - ./env/dev
  backend:
    env_file:
      - ./env/dev
  worker_channels:
    env_file:
      - ./env/dev
  frontend:
    ports:
      - '3000:3000'
    command: yarn start
  nginx:
    volumes:
      - ./nginx/nginx-proxy.dev.conf:/etc/nginx/conf.d/default.conf:ro
