export const FETCH_ORDERS = 'ORDERS/FETCH_ORDERS';
export const SET_ORDERS = 'ORDERS/SET_ORDERS';
export const CREATE_ORDER = 'ORDERS/CREATE_ORDER';
export const APPEND_ORDER = 'ORDERS/APPEND_ORDER';
export const UPDATE_NEW_ORDER = 'ORDERS/UPDATE_NEW_ORDER';
export const UPDATE_PAGE = 'ORDERS/UPDATE_PAGE';
export const ORDER_CREATED = 'ORDERS/ORDER_CREATED';
